// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4T6SA2Li1qavAUfOFaOi_WLI6BIQS4lI',
    appId: '1:882463732947:web:b1a71f5eacbfd42afbd026',
    messagingSenderId: '882463732947',
    projectId: 'electricalapp-2a278',
    authDomain: 'electricalapp-2a278.firebaseapp.com',
    storageBucket: 'electricalapp-2a278.firebasestorage.app',
    measurementId: 'G-EKV7920VV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8D7TuizEMBsSmmGLS0uTpaIRqyxZrkU',
    appId: '1:882463732947:android:b8aad335d405e547fbd026',
    messagingSenderId: '882463732947',
    projectId: 'electricalapp-2a278',
    storageBucket: 'electricalapp-2a278.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8wWUUDwQsK7GvUWX-mdPOiJPeRTw57Ws',
    appId: '1:882463732947:ios:0811704605f223a6fbd026',
    messagingSenderId: '882463732947',
    projectId: 'electricalapp-2a278',
    storageBucket: 'electricalapp-2a278.firebasestorage.app',
    iosBundleId: 'electricalapp',
  );

}